# Generated by Django 3.1.5 on 2021-01-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dna',
            name='matching_partner',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
